run("Duplicate...", "title=x");
run("Duplicate...", "title=sqrt(x^2+1)");
run("32-bit");
run("Square");
run("Add...", "value=1");
run("Square Root");
imageCalculator("Add create 32-bit", "x","sqrt(x^2+1)");
selectWindow("Result of x");
run("Log");
run("Enhance Contrast", "saturated=0.35");
selectWindow("sqrt(x^2+1)");
close();
selectWindow("x");
close();
rename("asinh transform");
